export const countries = [
  {
    name: 'Afganistán',
    dialCode: '+93',
    isoCode3: 'AFG',
    isoCode2: 'AF',
    flag: 'https://www.countryflags.io/AF/flat/24.png',
  },
  {
    name: 'Albania',
    dialCode: '+355',
    isoCode3: 'ALB',
    isoCode2: 'AL',
    flag: 'https://www.countryflags.io/AL/flat/24.png',
  },
  {
    name: 'Alemania',
    dialCode: '+49',
    isoCode3: 'DEU',
    isoCode2: 'DE',
    flag: 'https://www.countryflags.io/DE/flat/24.png',
  },
  {
    name: 'Andorra',
    dialCode: '+376',
    isoCode3: 'AND',
    isoCode2: 'AD',
    flag: 'https://www.countryflags.io/AD/flat/24.png',
  },
  {
    name: 'Angola',
    dialCode: '+244',
    isoCode3: 'AGO',
    isoCode2: 'AO',
    flag: 'https://www.countryflags.io/AO/flat/24.png',
  },
  {
    name: 'Anguila',
    dialCode: '+1264',
    isoCode3: 'AIA',
    isoCode2: 'AI',
    flag: 'https://www.countryflags.io/AI/flat/24.png',
  },
  {
    name: 'Antártida',
    dialCode: '+672',
    isoCode3: 'ATA',
    isoCode2: 'AQ',
    flag: 'https://www.countryflags.io/AQ/flat/24.png',
  },
  {
    name: 'Antigua y Barbuda',
    dialCode: '+1268',
    isoCode3: 'ATG',
    isoCode2: 'AG',
    flag: 'https://www.countryflags.io/AG/flat/24.png',
  },
  {
    name: 'Arabia Saudita',
    dialCode: '+966',
    isoCode3: 'SAU',
    isoCode2: 'SA',
    flag: 'https://www.countryflags.io/SA/flat/24.png',
  },
  {
    name: 'Argelia',
    dialCode: '+213',
    isoCode3: 'DZA',
    isoCode2: 'DZ',
    flag: 'https://www.countryflags.io/DZ/flat/24.png',
  },
  {
    name: 'Argentina',
    dialCode: '+54',
    isoCode3: 'ARG',
    isoCode2: 'AR',
    flag: 'https://www.countryflags.io/AR/flat/24.png',
  },
  {
    name: 'Armenia',
    dialCode: '+374',
    isoCode3: 'ARM',
    isoCode2: 'AM',
    flag: 'https://www.countryflags.io/AM/flat/24.png',
  },
  {
    name: 'Aruba',
    dialCode: '+297',
    isoCode3: 'ABW',
    isoCode2: 'AW',
    flag: 'https://www.countryflags.io/AW/flat/24.png',
  },
  {
    name: 'Australia',
    dialCode: '+61',
    isoCode3: 'AUS',
    isoCode2: 'AU',
    flag: 'https://www.countryflags.io/AU/flat/24.png',
  },
  {
    name: 'Austria',
    dialCode: '+43',
    isoCode3: 'AUT',
    isoCode2: 'AT',
    flag: 'https://www.countryflags.io/AT/flat/24.png',
  },
  {
    name: 'Azerbaiyán',
    dialCode: '+994',
    isoCode3: 'AZE',
    isoCode2: 'AZ',
    flag: 'https://www.countryflags.io/AZ/flat/24.png',
  },
  {
    name: 'Bélgica',
    dialCode: '+32',
    isoCode3: 'BEL',
    isoCode2: 'BE',
    flag: 'https://www.countryflags.io/BE/flat/24.png',
  },
  {
    name: 'Bahamas',
    dialCode: '+1242',
    isoCode3: 'BHS',
    isoCode2: 'BS',
    flag: 'https://www.countryflags.io/BS/flat/24.png',
  },
  {
    name: 'Bahrein',
    dialCode: '+973',
    isoCode3: 'BHR',
    isoCode2: 'BH',
    flag: 'https://www.countryflags.io/BH/flat/24.png',
  },
  {
    name: 'Bangladesh',
    dialCode: '+880',
    isoCode3: 'BGD',
    isoCode2: 'BD',
    flag: 'https://www.countryflags.io/BD/flat/24.png',
  },
  {
    name: 'Barbados',
    dialCode: '+1246',
    isoCode3: 'BRB',
    isoCode2: 'BB',
    flag: 'https://www.countryflags.io/BB/flat/24.png',
  },
  {
    name: 'Belice',
    dialCode: '+501',
    isoCode3: 'BLZ',
    isoCode2: 'BZ',
    flag: 'https://www.countryflags.io/BZ/flat/24.png',
  },
  {
    name: 'Benín',
    dialCode: '+229',
    isoCode3: 'BEN',
    isoCode2: 'BJ',
    flag: 'https://www.countryflags.io/BJ/flat/24.png',
  },
  {
    name: 'Bhután',
    dialCode: '+975',
    isoCode3: 'BTN',
    isoCode2: 'BT',
    flag: 'https://www.countryflags.io/BT/flat/24.png',
  },
  {
    name: 'Bielorrusia',
    dialCode: '+375',
    isoCode3: 'BLR',
    isoCode2: 'BY',
    flag: 'https://www.countryflags.io/BY/flat/24.png',
  },
  {
    name: 'Birmania',
    dialCode: '+95',
    isoCode3: 'MMR',
    isoCode2: 'MM',
    flag: 'https://www.countryflags.io/MM/flat/24.png',
  },
  {
    name: 'Bolivia',
    dialCode: '+591',
    isoCode3: 'BOL',
    isoCode2: 'BO',
    flag: 'https://www.countryflags.io/BO/flat/24.png',
  },
  {
    name: 'Bosnia y Herzegovina',
    dialCode: '+387',
    isoCode3: 'BIH',
    isoCode2: 'BA',
    flag: 'https://www.countryflags.io/BA/flat/24.png',
  },
  {
    name: 'Botsuana',
    dialCode: '+267',
    isoCode3: 'BWA',
    isoCode2: 'BW',
    flag: 'https://www.countryflags.io/BW/flat/24.png',
  },
  {
    name: 'Brasil',
    dialCode: '+55',
    isoCode3: 'BRA',
    isoCode2: 'BR',
    flag: 'https://www.countryflags.io/BR/flat/24.png',
  },
  {
    name: 'Brunéi',
    dialCode: '+673',
    isoCode3: 'BRN',
    isoCode2: 'BN',
    flag: 'https://www.countryflags.io/BN/flat/24.png',
  },
  {
    name: 'Bulgaria',
    dialCode: '+359',
    isoCode3: 'BGR',
    isoCode2: 'BG',
    flag: 'https://www.countryflags.io/BG/flat/24.png',
  },
  {
    name: 'Burkina Faso',
    dialCode: '+226',
    isoCode3: 'BFA',
    isoCode2: 'BF',
    flag: 'https://www.countryflags.io/BF/flat/24.png',
  },
  {
    name: 'Burundi',
    dialCode: '+257',
    isoCode3: 'BDI',
    isoCode2: 'BI',
    flag: 'https://www.countryflags.io/BI/flat/24.png',
  },
  {
    name: 'Cabo Verde',
    dialCode: '+238',
    isoCode3: 'CPV',
    isoCode2: 'CV',
    flag: 'https://www.countryflags.io/CV/flat/24.png',
  },
  {
    name: 'Camboya',
    dialCode: '+855',
    isoCode3: 'KHM',
    isoCode2: 'KH',
    flag: 'https://www.countryflags.io/KH/flat/24.png',
  },
  {
    name: 'Camerún',
    dialCode: '+237',
    isoCode3: 'CMR',
    isoCode2: 'CM',
    flag: 'https://www.countryflags.io/CM/flat/24.png',
  },
  // {
  //   name: 'Canadá',
  //   dialCode: '+1',
  //   isoCode3: 'CAN',
  //   isoCode2: 'CA',
  //   flag: 'https://www.countryflags.io/CA/flat/24.png',
  // },
  {
    name: 'Chad',
    dialCode: '+235',
    isoCode3: 'TCD',
    isoCode2: 'TD',
    flag: 'https://www.countryflags.io/TD/flat/24.png',
  },
  {
    name: 'Chile',
    dialCode: '+56',
    isoCode3: 'CHL',
    isoCode2: 'CL',
    flag: 'https://www.countryflags.io/CL/flat/24.png',
  },
  {
    name: 'China',
    dialCode: '+86',
    isoCode3: 'CHN',
    isoCode2: 'CN',
    flag: 'https://www.countryflags.io/CN/flat/24.png',
  },
  {
    name: 'Chipre',
    dialCode: '+357',
    isoCode3: 'CYP',
    isoCode2: 'CY',
    flag: 'https://www.countryflags.io/CY/flat/24.png',
  },
  {
    name: 'Ciudad del Vaticano',
    dialCode: '+39',
    isoCode3: 'VAT',
    isoCode2: 'VA',
    flag: 'https://www.countryflags.io/VA/flat/24.png',
  },
  {
    name: 'Colombia',
    dialCode: '+57',
    isoCode3: 'COL',
    isoCode2: 'CO',
    flag: 'https://www.countryflags.io/CO/flat/24.png',
  },
  {
    name: 'Comoras',
    dialCode: '+269',
    isoCode3: 'COM',
    isoCode2: 'KM',
    flag: 'https://www.countryflags.io/KM/flat/24.png',
  },
  {
    name: 'República del Congo',
    dialCode: '+242',
    isoCode3: 'COG',
    isoCode2: 'CG',
    flag: 'https://www.countryflags.io/CG/flat/24.png',
  },
  {
    name: 'República Democrática del Congo',
    dialCode: '+243',
    isoCode3: 'COD',
    isoCode2: 'CD',
    flag: 'https://www.countryflags.io/CD/flat/24.png',
  },
  {
    name: 'Corea del Norte',
    dialCode: '+850',
    isoCode3: 'PRK',
    isoCode2: 'KP',
    flag: 'https://www.countryflags.io/KP/flat/24.png',
  },
  {
    name: 'Corea del Sur',
    dialCode: '+82',
    isoCode3: 'KOR',
    isoCode2: 'KR',
    flag: 'https://www.countryflags.io/KR/flat/24.png',
  },
  {
    name: 'Costa de Marfil',
    dialCode: '+225',
    isoCode3: 'CIV',
    isoCode2: 'CI',
    flag: 'https://www.countryflags.io/CI/flat/24.png',
  },
  {
    name: 'Costa Rica',
    dialCode: '+506',
    isoCode3: 'CRI',
    isoCode2: 'CR',
    flag: 'https://www.countryflags.io/CR/flat/24.png',
  },
  {
    name: 'Croacia',
    dialCode: '+385',
    isoCode3: 'HRV',
    isoCode2: 'HR',
    flag: 'https://www.countryflags.io/HR/flat/24.png',
  },
  {
    name: 'Cuba',
    dialCode: '+53',
    isoCode3: 'CUB',
    isoCode2: 'CU',
    flag: 'https://www.countryflags.io/CU/flat/24.png',
  },
  {
    name: 'Curazao',
    dialCode: '+5999',
    isoCode3: 'CWU',
    isoCode2: 'CW',
    flag: 'https://www.countryflags.io/CW/flat/24.png',
  },
  {
    name: 'Dinamarca',
    dialCode: '+45',
    isoCode3: 'DNK',
    isoCode2: 'DK',
    flag: 'https://www.countryflags.io/DK/flat/24.png',
  },
  {
    name: 'Dominica',
    dialCode: '+1767',
    isoCode3: 'DMA',
    isoCode2: 'DM',
    flag: 'https://www.countryflags.io/DM/flat/24.png',
  },
  {
    name: 'Ecuador',
    dialCode: '+593',
    isoCode3: 'ECU',
    isoCode2: 'EC',
    flag: 'https://www.countryflags.io/EC/flat/24.png',
  },
  {
    name: 'Egipto',
    dialCode: '+20',
    isoCode3: 'EGY',
    isoCode2: 'EG',
    flag: 'https://www.countryflags.io/EG/flat/24.png',
  },
  {
    name: 'El Salvador',
    dialCode: '+503',
    isoCode3: 'SLV',
    isoCode2: 'SV',
    flag: 'https://www.countryflags.io/SV/flat/24.png',
  },
  {
    name: 'Emiratos Árabes Unidos',
    dialCode: '+971',
    isoCode3: 'ARE',
    isoCode2: 'AE',
    flag: 'https://www.countryflags.io/AE/flat/24.png',
  },
  {
    name: 'Eritrea',
    dialCode: '+291',
    isoCode3: 'ERI',
    isoCode2: 'ER',
    flag: 'https://www.countryflags.io/ER/flat/24.png',
  },
  {
    name: 'Eslovaquia',
    dialCode: '+421',
    isoCode3: 'SVK',
    isoCode2: 'SK',
    flag: 'https://www.countryflags.io/SK/flat/24.png',
  },
  {
    name: 'Eslovenia',
    dialCode: '+386',
    isoCode3: 'SVN',
    isoCode2: 'SI',
    flag: 'https://www.countryflags.io/SI/flat/24.png',
  },
  {
    name: 'España',
    dialCode: '+34',
    isoCode3: 'ESP',
    isoCode2: 'ES',
    flag: 'https://www.countryflags.io/ES/flat/24.png',
  },
  {
    name: 'Estados Unidos de América / Cánada / Puerto Rico',
    dialCode: '+1',
    isoCode3: 'USA',
    isoCode2: 'US',
    flag: 'https://www.countryflags.io/US/flat/24.png',
  },
  {
    name: 'Estonia',
    dialCode: '+372',
    isoCode3: 'EST',
    isoCode2: 'EE',
    flag: 'https://www.countryflags.io/EE/flat/24.png',
  },
  {
    name: 'Etiopía',
    dialCode: '+251',
    isoCode3: 'ETH',
    isoCode2: 'ET',
    flag: 'https://www.countryflags.io/ET/flat/24.png',
  },
  {
    name: 'Filipinas',
    dialCode: '+63',
    isoCode3: 'PHL',
    isoCode2: 'PH',
    flag: 'https://www.countryflags.io/PH/flat/24.png',
  },
  {
    name: 'Finlandia',
    dialCode: '+358',
    isoCode3: 'FIN',
    isoCode2: 'FI',
    flag: 'https://www.countryflags.io/FI/flat/24.png',
  },
  {
    name: 'Fiyi',
    dialCode: '+679',
    isoCode3: 'FJI',
    isoCode2: 'FJ',
    flag: 'https://www.countryflags.io/FJ/flat/24.png',
  },
  {
    name: 'Francia',
    dialCode: '+33',
    isoCode3: 'FRA',
    isoCode2: 'FR',
    flag: 'https://www.countryflags.io/FR/flat/24.png',
  },
  {
    name: 'Gabón',
    dialCode: '+241',
    isoCode3: 'GAB',
    isoCode2: 'GA',
    flag: 'https://www.countryflags.io/GA/flat/24.png',
  },
  {
    name: 'Gambia',
    dialCode: '+220',
    isoCode3: 'GMB',
    isoCode2: 'GM',
    flag: 'https://www.countryflags.io/GM/flat/24.png',
  },
  {
    name: 'Georgia',
    dialCode: '+995',
    isoCode3: 'GEO',
    isoCode2: 'GE',
    flag: 'https://www.countryflags.io/GE/flat/24.png',
  },
  {
    name: 'Ghana',
    dialCode: '+233',
    isoCode3: 'GHA',
    isoCode2: 'GH',
    flag: 'https://www.countryflags.io/GH/flat/24.png',
  },
  {
    name: 'Gibraltar',
    dialCode: '+350',
    isoCode3: 'GIB',
    isoCode2: 'GI',
    flag: 'https://www.countryflags.io/GI/flat/24.png',
  },
  {
    name: 'Granada',
    dialCode: '+1473',
    isoCode3: 'GRD',
    isoCode2: 'GD',
    flag: 'https://www.countryflags.io/GD/flat/24.png',
  },
  {
    name: 'Grecia',
    dialCode: '+30',
    isoCode3: 'GRC',
    isoCode2: 'GR',
    flag: 'https://www.countryflags.io/GR/flat/24.png',
  },
  {
    name: 'Groenlandia',
    dialCode: '+299',
    isoCode3: 'GRL',
    isoCode2: 'GL',
    flag: 'https://www.countryflags.io/GL/flat/24.png',
  },
  {
    name: 'Guadalupe',
    dialCode: '+590',
    isoCode3: 'GLP',
    isoCode2: 'GP',
    flag: 'https://www.countryflags.io/GP/flat/24.png',
  },
  {
    name: 'Guam',
    dialCode: '+1671',
    isoCode3: 'GUM',
    isoCode2: 'GU',
    flag: 'https://www.countryflags.io/GU/flat/24.png',
  },
  {
    name: 'Guatemala',
    dialCode: '+502',
    isoCode3: 'GTM',
    isoCode2: 'GT',
    flag: 'https://www.countryflags.io/GT/flat/24.png',
  },
  {
    name: 'Guayana Francesa',
    dialCode: '+594',
    isoCode3: 'GUF',
    isoCode2: 'GF',
    flag: 'https://www.countryflags.io/GF/flat/24.png',
  },
  {
    name: 'Guernsey',
    dialCode: '+44',
    isoCode3: 'GGY',
    isoCode2: 'GG',
    flag: 'https://www.countryflags.io/GG/flat/24.png',
  },
  {
    name: 'Guinea',
    dialCode: '+224',
    isoCode3: 'GIN',
    isoCode2: 'GN',
    flag: 'https://www.countryflags.io/GN/flat/24.png',
  },
  {
    name: 'Guinea Ecuatorial',
    dialCode: '+240',
    isoCode3: 'GNQ',
    isoCode2: 'GQ',
    flag: 'https://www.countryflags.io/GQ/flat/24.png',
  },
  {
    name: 'Guinea-Bissau',
    dialCode: '+245',
    isoCode3: 'GNB',
    isoCode2: 'GW',
    flag: 'https://www.countryflags.io/GW/flat/24.png',
  },
  {
    name: 'Guyana',
    dialCode: '+592',
    isoCode3: 'GUY',
    isoCode2: 'GY',
    flag: 'https://www.countryflags.io/GY/flat/24.png',
  },
  {
    name: 'Haití',
    dialCode: '+509',
    isoCode3: 'HTI',
    isoCode2: 'HT',
    flag: 'https://www.countryflags.io/HT/flat/24.png',
  },
  {
    name: 'Honduras',
    dialCode: '+504',
    isoCode3: 'HND',
    isoCode2: 'HN',
    flag: 'https://www.countryflags.io/HN/flat/24.png',
  },
  {
    name: 'Hong kong',
    dialCode: '+852',
    isoCode3: 'HKG',
    isoCode2: 'HK',
    flag: 'https://www.countryflags.io/HK/flat/24.png',
  },
  {
    name: 'Hungría',
    dialCode: '+36',
    isoCode3: 'HUN',
    isoCode2: 'HU',
    flag: 'https://www.countryflags.io/HU/flat/24.png',
  },
  {
    name: 'India',
    dialCode: '+91',
    isoCode3: 'IND',
    isoCode2: 'IN',
    flag: 'https://www.countryflags.io/IN/flat/24.png',
  },
  {
    name: 'Indonesia',
    dialCode: '+62',
    isoCode3: 'IDN',
    isoCode2: 'ID',
    flag: 'https://www.countryflags.io/ID/flat/24.png',
  },
  {
    name: 'Irán',
    dialCode: '+98',
    isoCode3: 'IRN',
    isoCode2: 'IR',
    flag: 'https://www.countryflags.io/IR/flat/24.png',
  },
  {
    name: 'Irak',
    dialCode: '+964',
    isoCode3: 'IRQ',
    isoCode2: 'IQ',
    flag: 'https://www.countryflags.io/IQ/flat/24.png',
  },
  {
    name: 'Irlanda',
    dialCode: '+353',
    isoCode3: 'IRL',
    isoCode2: 'IE',
    flag: 'https://www.countryflags.io/IE/flat/24.png',
  },
  {
    name: 'Isla de Man',
    dialCode: '+44',
    isoCode3: 'IMN',
    isoCode2: 'IM',
    flag: 'https://www.countryflags.io/IM/flat/24.png',
  },
  {
    name: 'Isla de Navidad',
    dialCode: '+61',
    isoCode3: 'CXR',
    isoCode2: 'CX',
    flag: 'https://www.countryflags.io/CX/flat/24.png',
  },
  {
    name: 'Isla Norfolk',
    dialCode: '+672',
    isoCode3: 'NFK',
    isoCode2: 'NF',
    flag: 'https://www.countryflags.io/NF/flat/24.png',
  },
  {
    name: 'Islandia',
    dialCode: '+354',
    isoCode3: 'ISL',
    isoCode2: 'IS',
    flag: 'https://www.countryflags.io/IS/flat/24.png',
  },
  {
    name: 'Islas Bermudas',
    dialCode: '+1441',
    isoCode3: 'BMU',
    isoCode2: 'BM',
    flag: 'https://www.countryflags.io/BM/flat/24.png',
  },
  {
    name: 'Islas Caimán',
    dialCode: '+1345',
    isoCode3: 'CYM',
    isoCode2: 'KY',
    flag: 'https://www.countryflags.io/KY/flat/24.png',
  },
  {
    name: 'Islas Cocos (Keeling)',
    dialCode: '+61',
    isoCode3: 'CCK',
    isoCode2: 'CC',
    flag: 'https://www.countryflags.io/CC/flat/24.png',
  },
  {
    name: 'Islas Cook',
    dialCode: '+682',
    isoCode3: 'COK',
    isoCode2: 'CK',
    flag: 'https://www.countryflags.io/CK/flat/24.png',
  },
  {
    name: 'Islas de Åland',
    dialCode: '+358',
    isoCode3: 'ALA',
    isoCode2: 'AX',
    flag: 'https://www.countryflags.io/AX/flat/24.png',
  },
  {
    name: 'Islas Feroe',
    dialCode: '+298',
    isoCode3: 'FRO',
    isoCode2: 'FO',
    flag: 'https://www.countryflags.io/FO/flat/24.png',
  },
  {
    name: 'Islas Georgias del Sur y Sandwich del Sur',
    dialCode: '+500',
    isoCode3: 'SGS',
    isoCode2: 'GS',
    flag: 'https://www.countryflags.io/GS/flat/24.png',
  },
  {
    name: 'Islas Maldivas',
    dialCode: '+960',
    isoCode3: 'MDV',
    isoCode2: 'MV',
    flag: 'https://www.countryflags.io/MV/flat/24.png',
  },
  {
    name: 'Islas Malvinas',
    dialCode: '+500',
    isoCode3: 'FLK',
    isoCode2: 'FK',
    flag: 'https://www.countryflags.io/FK/flat/24.png',
  },
  {
    name: 'Islas Marianas del Norte',
    dialCode: '+1670',
    isoCode3: 'MNP',
    isoCode2: 'MP',
    flag: 'https://www.countryflags.io/MP/flat/24.png',
  },
  {
    name: 'Islas Marshall',
    dialCode: '+692',
    isoCode3: 'MHL',
    isoCode2: 'MH',
    flag: 'https://www.countryflags.io/MH/flat/24.png',
  },
  {
    name: 'Islas Pitcairn',
    dialCode: '+870',
    isoCode3: 'PCN',
    isoCode2: 'PN',
    flag: 'https://www.countryflags.io/PN/flat/24.png',
  },
  {
    name: 'Islas Salomón',
    dialCode: '+677',
    isoCode3: 'SLB',
    isoCode2: 'SB',
    flag: 'https://www.countryflags.io/SB/flat/24.png',
  },
  {
    name: 'Islas Turcas y Caicos',
    dialCode: '+1649',
    isoCode3: 'TCA',
    isoCode2: 'TC',
    flag: 'https://www.countryflags.io/TC/flat/24.png',
  },
  {
    name: 'Islas Ultramarinas Menores de Estados Unidos',
    dialCode: '+246',
    isoCode3: 'UMI',
    isoCode2: 'UM',
    flag: 'https://www.countryflags.io/UM/flat/24.png',
  },
  {
    name: 'Islas Vírgenes Británicas',
    dialCode: '+1284',
    isoCode3: 'VGB',
    isoCode2: 'VG',
    flag: 'https://www.countryflags.io/VG/flat/24.png',
  },
  {
    name: 'Islas Vírgenes de los Estados Unidos',
    dialCode: '+1340',
    isoCode3: 'VIR',
    isoCode2: 'VI',
    flag: 'https://www.countryflags.io/VI/flat/24.png',
  },
  {
    name: 'Israel',
    dialCode: '+972',
    isoCode3: 'ISR',
    isoCode2: 'IL',
    flag: 'https://www.countryflags.io/IL/flat/24.png',
  },
  {
    name: 'Italia',
    dialCode: '+39',
    isoCode3: 'ITA',
    isoCode2: 'IT',
    flag: 'https://www.countryflags.io/IT/flat/24.png',
  },
  {
    name: 'Jamaica',
    dialCode: '+1876',
    isoCode3: 'JAM',
    isoCode2: 'JM',
    flag: 'https://www.countryflags.io/JM/flat/24.png',
  },
  {
    name: 'Japón',
    dialCode: '+81',
    isoCode3: 'JPN',
    isoCode2: 'JP',
    flag: 'https://www.countryflags.io/JP/flat/24.png',
  },
  {
    name: 'Jersey',
    dialCode: '+44',
    isoCode3: 'JEY',
    isoCode2: 'JE',
    flag: 'https://www.countryflags.io/JE/flat/24.png',
  },
  {
    name: 'Jordania',
    dialCode: '+962',
    isoCode3: 'JOR',
    isoCode2: 'JO',
    flag: 'https://www.countryflags.io/JO/flat/24.png',
  },
  {
    name: 'Kazajistán',
    dialCode: '+7',
    isoCode3: 'KAZ',
    isoCode2: 'KZ',
    flag: 'https://www.countryflags.io/KZ/flat/24.png',
  },
  {
    name: 'Kenia',
    dialCode: '+254',
    isoCode3: 'KEN',
    isoCode2: 'KE',
    flag: 'https://www.countryflags.io/KE/flat/24.png',
  },
  {
    name: 'Kirguistán',
    dialCode: '+996',
    isoCode3: 'KGZ',
    isoCode2: 'KG',
    flag: 'https://www.countryflags.io/KG/flat/24.png',
  },
  {
    name: 'Kiribati',
    dialCode: '+686',
    isoCode3: 'KIR',
    isoCode2: 'KI',
    flag: 'https://www.countryflags.io/KI/flat/24.png',
  },
  {
    name: 'Kuwait',
    dialCode: '+965',
    isoCode3: 'KWT',
    isoCode2: 'KW',
    flag: 'https://www.countryflags.io/KW/flat/24.png',
  },
  {
    name: 'Líbano',
    dialCode: '+961',
    isoCode3: 'LBN',
    isoCode2: 'LB',
    flag: 'https://www.countryflags.io/LB/flat/24.png',
  },
  {
    name: 'Laos',
    dialCode: '+856',
    isoCode3: 'LAO',
    isoCode2: 'LA',
    flag: 'https://www.countryflags.io/LA/flat/24.png',
  },
  {
    name: 'Lesoto',
    dialCode: '+266',
    isoCode3: 'LSO',
    isoCode2: 'LS',
    flag: 'https://www.countryflags.io/LS/flat/24.png',
  },
  {
    name: 'Letonia',
    dialCode: '+371',
    isoCode3: 'LVA',
    isoCode2: 'LV',
    flag: 'https://www.countryflags.io/LV/flat/24.png',
  },
  {
    name: 'Liberia',
    dialCode: '+231',
    isoCode3: 'LBR',
    isoCode2: 'LR',
    flag: 'https://www.countryflags.io/LR/flat/24.png',
  },
  {
    name: 'Libia',
    dialCode: '+218',
    isoCode3: 'LBY',
    isoCode2: 'LY',
    flag: 'https://www.countryflags.io/LY/flat/24.png',
  },
  {
    name: 'Liechtenstein',
    dialCode: '+423',
    isoCode3: 'LIE',
    isoCode2: 'LI',
    flag: 'https://www.countryflags.io/LI/flat/24.png',
  },
  {
    name: 'Lituania',
    dialCode: '+370',
    isoCode3: 'LTU',
    isoCode2: 'LT',
    flag: 'https://www.countryflags.io/LT/flat/24.png',
  },
  {
    name: 'Luxemburgo',
    dialCode: '+352',
    isoCode3: 'LUX',
    isoCode2: 'LU',
    flag: 'https://www.countryflags.io/LU/flat/24.png',
  },
  {
    name: 'México',
    dialCode: '+52',
    isoCode3: 'MEX',
    isoCode2: 'MX',
    flag: 'https://www.countryflags.io/MX/flat/24.png',
  },
  {
    name: 'Mónaco',
    dialCode: '+377',
    isoCode3: 'MCO',
    isoCode2: 'MC',
    flag: 'https://www.countryflags.io/MC/flat/24.png',
  },
  {
    name: 'Macao',
    dialCode: '+853',
    isoCode3: 'MAC',
    isoCode2: 'MO',
    flag: 'https://www.countryflags.io/MO/flat/24.png',
  },
  {
    name: 'Macedônia',
    dialCode: '+389',
    isoCode3: 'MKD',
    isoCode2: 'MK',
    flag: 'https://www.countryflags.io/MK/flat/24.png',
  },
  {
    name: 'Madagascar',
    dialCode: '+261',
    isoCode3: 'MDG',
    isoCode2: 'MG',
    flag: 'https://www.countryflags.io/MG/flat/24.png',
  },
  {
    name: 'Malasia',
    dialCode: '+60',
    isoCode3: 'MYS',
    isoCode2: 'MY',
    flag: 'https://www.countryflags.io/MY/flat/24.png',
  },
  {
    name: 'Malawi',
    dialCode: '+265',
    isoCode3: 'MWI',
    isoCode2: 'MW',
    flag: 'https://www.countryflags.io/MW/flat/24.png',
  },
  {
    name: 'Mali',
    dialCode: '+223',
    isoCode3: 'MLI',
    isoCode2: 'ML',
    flag: 'https://www.countryflags.io/ML/flat/24.png',
  },
  {
    name: 'Malta',
    dialCode: '+356',
    isoCode3: 'MLT',
    isoCode2: 'MT',
    flag: 'https://www.countryflags.io/MT/flat/24.png',
  },
  {
    name: 'Marruecos',
    dialCode: '+212',
    isoCode3: 'MAR',
    isoCode2: 'MA',
    flag: 'https://www.countryflags.io/MA/flat/24.png',
  },
  {
    name: 'Martinica',
    dialCode: '+596',
    isoCode3: 'MTQ',
    isoCode2: 'MQ',
    flag: 'https://www.countryflags.io/MQ/flat/24.png',
  },
  {
    name: 'Mauricio',
    dialCode: '+230',
    isoCode3: 'MUS',
    isoCode2: 'MU',
    flag: 'https://www.countryflags.io/MU/flat/24.png',
  },
  {
    name: 'Mauritania',
    dialCode: '+222',
    isoCode3: 'MRT',
    isoCode2: 'MR',
    flag: 'https://www.countryflags.io/MR/flat/24.png',
  },
  {
    name: 'Mayotte',
    dialCode: '+262',
    isoCode3: 'MYT',
    isoCode2: 'YT',
    flag: 'https://www.countryflags.io/YT/flat/24.png',
  },
  {
    name: 'Micronesia',
    dialCode: '+691',
    isoCode3: 'FSM',
    isoCode2: 'FM',
    flag: 'https://www.countryflags.io/FM/flat/24.png',
  },
  {
    name: 'Moldavia',
    dialCode: '+373',
    isoCode3: 'MDA',
    isoCode2: 'MD',
    flag: 'https://www.countryflags.io/MD/flat/24.png',
  },
  {
    name: 'Mongolia',
    dialCode: '+976',
    isoCode3: 'MNG',
    isoCode2: 'MN',
    flag: 'https://www.countryflags.io/MN/flat/24.png',
  },
  {
    name: 'Montenegro',
    dialCode: '+382',
    isoCode3: 'MNE',
    isoCode2: 'ME',
    flag: 'https://www.countryflags.io/ME/flat/24.png',
  },
  {
    name: 'Montserrat',
    dialCode: '+1664',
    isoCode3: 'MSR',
    isoCode2: 'MS',
    flag: 'https://www.countryflags.io/MS/flat/24.png',
  },
  {
    name: 'Mozambique',
    dialCode: '+258',
    isoCode3: 'MOZ',
    isoCode2: 'MZ',
    flag: 'https://www.countryflags.io/MZ/flat/24.png',
  },
  {
    name: 'Namibia',
    dialCode: '+264',
    isoCode3: 'NAM',
    isoCode2: 'NA',
    flag: 'https://www.countryflags.io/NA/flat/24.png',
  },
  {
    name: 'Nauru',
    dialCode: '+674',
    isoCode3: 'NRU',
    isoCode2: 'NR',
    flag: 'https://www.countryflags.io/NR/flat/24.png',
  },
  {
    name: 'Nepal',
    dialCode: '+977',
    isoCode3: 'NPL',
    isoCode2: 'NP',
    flag: 'https://www.countryflags.io/NP/flat/24.png',
  },
  {
    name: 'Nicaragua',
    dialCode: '+505',
    isoCode3: 'NIC',
    isoCode2: 'NI',
    flag: 'https://www.countryflags.io/NI/flat/24.png',
  },
  {
    name: 'Niger',
    dialCode: '+227',
    isoCode3: 'NER',
    isoCode2: 'NE',
    flag: 'https://www.countryflags.io/NE/flat/24.png',
  },
  {
    name: 'Nigeria',
    dialCode: '+234',
    isoCode3: 'NGA',
    isoCode2: 'NG',
    flag: 'https://www.countryflags.io/NG/flat/24.png',
  },
  {
    name: 'Niue',
    dialCode: '+683',
    isoCode3: 'NIU',
    isoCode2: 'NU',
    flag: 'https://www.countryflags.io/NU/flat/24.png',
  },
  {
    name: 'Noruega',
    dialCode: '+47',
    isoCode3: 'NOR',
    isoCode2: 'NO',
    flag: 'https://www.countryflags.io/NO/flat/24.png',
  },
  {
    name: 'Nueva Caledonia',
    dialCode: '+687',
    isoCode3: 'NCL',
    isoCode2: 'NC',
    flag: 'https://www.countryflags.io/NC/flat/24.png',
  },
  {
    name: 'Nueva Zelanda',
    dialCode: '+64',
    isoCode3: 'NZL',
    isoCode2: 'NZ',
    flag: 'https://www.countryflags.io/NZ/flat/24.png',
  },
  {
    name: 'Omán',
    dialCode: '+968',
    isoCode3: 'OMN',
    isoCode2: 'OM',
    flag: 'https://www.countryflags.io/OM/flat/24.png',
  },
  {
    name: 'Países Bajos',
    dialCode: '+31',
    isoCode3: 'NLD',
    isoCode2: 'NL',
    flag: 'https://www.countryflags.io/NL/flat/24.png',
  },
  {
    name: 'Pakistán',
    dialCode: '+92',
    isoCode3: 'PAK',
    isoCode2: 'PK',
    flag: 'https://www.countryflags.io/PK/flat/24.png',
  },
  {
    name: 'Palau',
    dialCode: '+680',
    isoCode3: 'PLW',
    isoCode2: 'PW',
    flag: 'https://www.countryflags.io/PW/flat/24.png',
  },
  {
    name: 'Palestina',
    dialCode: '+970',
    isoCode3: 'PSE',
    isoCode2: 'PS',
    flag: 'https://www.countryflags.io/PS/flat/24.png',
  },
  {
    name: 'Panamá',
    dialCode: '+507',
    isoCode3: 'PAN',
    isoCode2: 'PA',
    flag: 'https://www.countryflags.io/PA/flat/24.png',
  },
  {
    name: 'Papúa Nueva Guinea',
    dialCode: '+675',
    isoCode3: 'PNG',
    isoCode2: 'PG',
    flag: 'https://www.countryflags.io/PG/flat/24.png',
  },
  {
    name: 'Paraguay',
    dialCode: '+595',
    isoCode3: 'PRY',
    isoCode2: 'PY',
    flag: 'https://www.countryflags.io/PY/flat/24.png',
  },
  {
    name: 'Perú',
    dialCode: '+51',
    isoCode3: 'PER',
    isoCode2: 'PE',
    flag: 'https://www.countryflags.io/PE/flat/24.png',
  },
  {
    name: 'Polinesia Francesa',
    dialCode: '+689',
    isoCode3: 'PYF',
    isoCode2: 'PF',
    flag: 'https://www.countryflags.io/PF/flat/24.png',
  },
  {
    name: 'Polonia',
    dialCode: '+48',
    isoCode3: 'POL',
    isoCode2: 'PL',
    flag: 'https://www.countryflags.io/PL/flat/24.png',
  },
  {
    name: 'Portugal',
    dialCode: '+351',
    isoCode3: 'PRT',
    isoCode2: 'PT',
    flag: 'https://www.countryflags.io/PT/flat/24.png',
  },
  // {
  //   name: 'Puerto Rico',
  //   dialCode: '+1',
  //   isoCode3: 'PRI',
  //   isoCode2: 'PR',
  //   flag: 'https://www.countryflags.io/PR/flat/24.png',
  // },
  {
    name: 'Qatar',
    dialCode: '+974',
    isoCode3: 'QAT',
    isoCode2: 'QA',
    flag: 'https://www.countryflags.io/QA/flat/24.png',
  },
  {
    name: 'Reino Unido',
    dialCode: '+44',
    isoCode3: 'GBR',
    isoCode2: 'GB',
    flag: 'https://www.countryflags.io/GB/flat/24.png',
  },
  {
    name: 'República Centroafricana',
    dialCode: '+236',
    isoCode3: 'CAF',
    isoCode2: 'CF',
    flag: 'https://www.countryflags.io/CF/flat/24.png',
  },
  {
    name: 'República Checa',
    dialCode: '+420',
    isoCode3: 'CZE',
    isoCode2: 'CZ',
    flag: 'https://www.countryflags.io/CZ/flat/24.png',
  },
  {
    name: 'República Dominicana',
    dialCode: '+1809',
    isoCode3: 'DOM',
    isoCode2: 'DO',
    flag: 'https://www.countryflags.io/DO/flat/24.png',
  },
  {
    name: 'República de Sudán del Sur',
    dialCode: '+211',
    isoCode3: 'SSD',
    isoCode2: 'SS',
    flag: 'https://www.countryflags.io/SS/flat/24.png',
  },
  {
    name: 'Reunión',
    dialCode: '+262',
    isoCode3: 'REU',
    isoCode2: 'RE',
    flag: 'https://www.countryflags.io/RE/flat/24.png',
  },
  {
    name: 'Ruanda',
    dialCode: '+250',
    isoCode3: 'RWA',
    isoCode2: 'RW',
    flag: 'https://www.countryflags.io/RW/flat/24.png',
  },
  {
    name: 'Rumanía',
    dialCode: '+40',
    isoCode3: 'ROU',
    isoCode2: 'RO',
    flag: 'https://www.countryflags.io/RO/flat/24.png',
  },
  {
    name: 'Rusia',
    dialCode: '+7',
    isoCode3: 'RUS',
    isoCode2: 'RU',
    flag: 'https://www.countryflags.io/RU/flat/24.png',
  },
  {
    name: 'Sahara Occidental',
    dialCode: '+212',
    isoCode3: 'ESH',
    isoCode2: 'EH',
    flag: 'https://www.countryflags.io/EH/flat/24.png',
  },
  {
    name: 'Samoa',
    dialCode: '+685',
    isoCode3: 'WSM',
    isoCode2: 'WS',
    flag: 'https://www.countryflags.io/WS/flat/24.png',
  },
  {
    name: 'Samoa Americana',
    dialCode: '+1684',
    isoCode3: 'ASM',
    isoCode2: 'AS',
    flag: 'https://www.countryflags.io/AS/flat/24.png',
  },
  {
    name: 'San Bartolomé',
    dialCode: '+590',
    isoCode3: 'BLM',
    isoCode2: 'BL',
    flag: 'https://www.countryflags.io/BL/flat/24.png',
  },
  {
    name: 'San Cristóbal y Nieves',
    dialCode: '+1869',
    isoCode3: 'KNA',
    isoCode2: 'KN',
    flag: 'https://www.countryflags.io/KN/flat/24.png',
  },
  {
    name: 'San Marino',
    dialCode: '+378',
    isoCode3: 'SMR',
    isoCode2: 'SM',
    flag: 'https://www.countryflags.io/SM/flat/24.png',
  },
  {
    name: 'San Martín (Francia)',
    dialCode: '+1599',
    isoCode3: 'MAF',
    isoCode2: 'MF',
    flag: 'https://www.countryflags.io/MF/flat/24.png',
  },
  {
    name: 'San Pedro y Miquelón',
    dialCode: '+508',
    isoCode3: 'SPM',
    isoCode2: 'PM',
    flag: 'https://www.countryflags.io/PM/flat/24.png',
  },
  {
    name: 'San Vicente y las Granadinas',
    dialCode: '+1784',
    isoCode3: 'VCT',
    isoCode2: 'VC',
    flag: 'https://www.countryflags.io/VC/flat/24.png',
  },
  {
    name: 'Santa Elena',
    dialCode: '+290',
    isoCode3: 'SHN',
    isoCode2: 'SH',
    flag: 'https://www.countryflags.io/SH/flat/24.png',
  },
  {
    name: 'Santa Lucía',
    dialCode: '+1758',
    isoCode3: 'LCA',
    isoCode2: 'LC',
    flag: 'https://www.countryflags.io/LC/flat/24.png',
  },
  {
    name: 'Santo Tomé y Príncipe',
    dialCode: '+239',
    isoCode3: 'STP',
    isoCode2: 'ST',
    flag: 'https://www.countryflags.io/ST/flat/24.png',
  },
  {
    name: 'Senegal',
    dialCode: '+221',
    isoCode3: 'SEN',
    isoCode2: 'SN',
    flag: 'https://www.countryflags.io/SN/flat/24.png',
  },
  {
    name: 'Serbia',
    dialCode: '+381',
    isoCode3: 'SRB',
    isoCode2: 'RS',
    flag: 'https://www.countryflags.io/RS/flat/24.png',
  },
  {
    name: 'Seychelles',
    dialCode: '+248',
    isoCode3: 'SYC',
    isoCode2: 'SC',
    flag: 'https://www.countryflags.io/SC/flat/24.png',
  },
  {
    name: 'Sierra Leona',
    dialCode: '+232',
    isoCode3: 'SLE',
    isoCode2: 'SL',
    flag: 'https://www.countryflags.io/SL/flat/24.png',
  },
  {
    name: 'Singapur',
    dialCode: '+65',
    isoCode3: 'SGP',
    isoCode2: 'SG',
    flag: 'https://www.countryflags.io/SG/flat/24.png',
  },
  {
    name: 'Sint Maarten',
    dialCode: '+1721',
    isoCode3: 'SMX',
    isoCode2: 'SX',
    flag: 'https://www.countryflags.io/SX/flat/24.png',
  },
  {
    name: 'Siria',
    dialCode: '+963',
    isoCode3: 'SYR',
    isoCode2: 'SY',
    flag: 'https://www.countryflags.io/SY/flat/24.png',
  },
  {
    name: 'Somalia',
    dialCode: '+252',
    isoCode3: 'SOM',
    isoCode2: 'SO',
    flag: 'https://www.countryflags.io/SO/flat/24.png',
  },
  {
    name: 'Sri lanka',
    dialCode: '+94',
    isoCode3: 'LKA',
    isoCode2: 'LK',
    flag: 'https://www.countryflags.io/LK/flat/24.png',
  },
  {
    name: 'Sudáfrica',
    dialCode: '+27',
    isoCode3: 'ZAF',
    isoCode2: 'ZA',
    flag: 'https://www.countryflags.io/ZA/flat/24.png',
  },
  {
    name: 'Sudán',
    dialCode: '+249',
    isoCode3: 'SDN',
    isoCode2: 'SD',
    flag: 'https://www.countryflags.io/SD/flat/24.png',
  },
  {
    name: 'Suecia',
    dialCode: '+46',
    isoCode3: 'SWE',
    isoCode2: 'SE',
    flag: 'https://www.countryflags.io/SE/flat/24.png',
  },
  {
    name: 'Suiza',
    dialCode: '+41',
    isoCode3: 'CHE',
    isoCode2: 'CH',
    flag: 'https://www.countryflags.io/CH/flat/24.png',
  },
  {
    name: 'Surinám',
    dialCode: '+597',
    isoCode3: 'SUR',
    isoCode2: 'SR',
    flag: 'https://www.countryflags.io/SR/flat/24.png',
  },
  {
    name: 'Svalbard y Jan Mayen',
    dialCode: '+47',
    isoCode3: 'SJM',
    isoCode2: 'SJ',
    flag: 'https://www.countryflags.io/SJ/flat/24.png',
  },
  {
    name: 'Swazilandia',
    dialCode: '+268',
    isoCode3: 'SWZ',
    isoCode2: 'SZ',
    flag: 'https://www.countryflags.io/SZ/flat/24.png',
  },
  {
    name: 'Tayikistán',
    dialCode: '+992',
    isoCode3: 'TJK',
    isoCode2: 'TJ',
    flag: 'https://www.countryflags.io/TJ/flat/24.png',
  },
  {
    name: 'Tailandia',
    dialCode: '+66',
    isoCode3: 'THA',
    isoCode2: 'TH',
    flag: 'https://www.countryflags.io/TH/flat/24.png',
  },
  {
    name: 'Taiwán',
    dialCode: '+886',
    isoCode3: 'TWN',
    isoCode2: 'TW',
    flag: 'https://www.countryflags.io/TW/flat/24.png',
  },
  {
    name: 'Tanzania',
    dialCode: '+255',
    isoCode3: 'TZA',
    isoCode2: 'TZ',
    flag: 'https://www.countryflags.io/TZ/flat/24.png',
  },
  {
    name: 'Territorio Británico del Océano Índico',
    dialCode: '+246',
    isoCode3: 'IOT',
    isoCode2: 'IO',
    flag: 'https://www.countryflags.io/IO/flat/24.png',
  },
  {
    name: 'Territorios Australes y Antárticas Franceses',
    dialCode: '+',
    isoCode3: 'ATF',
    isoCode2: 'TF',
    flag: 'https://www.countryflags.io/TF/flat/24.png',
  },
  {
    name: 'Timor Oriental',
    dialCode: '+670',
    isoCode3: 'TLS',
    isoCode2: 'TL',
    flag: 'https://www.countryflags.io/TL/flat/24.png',
  },
  {
    name: 'Togo',
    dialCode: '+228',
    isoCode3: 'TGO',
    isoCode2: 'TG',
    flag: 'https://www.countryflags.io/TG/flat/24.png',
  },
  {
    name: 'Tokelau',
    dialCode: '+690',
    isoCode3: 'TKL',
    isoCode2: 'TK',
    flag: 'https://www.countryflags.io/TK/flat/24.png',
  },
  {
    name: 'Tonga',
    dialCode: '+676',
    isoCode3: 'TON',
    isoCode2: 'TO',
    flag: 'https://www.countryflags.io/TO/flat/24.png',
  },
  {
    name: 'Trinidad y Tobago',
    dialCode: '+1868',
    isoCode3: 'TTO',
    isoCode2: 'TT',
    flag: 'https://www.countryflags.io/TT/flat/24.png',
  },
  {
    name: 'Tunez',
    dialCode: '+216',
    isoCode3: 'TUN',
    isoCode2: 'TN',
    flag: 'https://www.countryflags.io/TN/flat/24.png',
  },
  {
    name: 'Turkmenistán',
    dialCode: '+993',
    isoCode3: 'TKM',
    isoCode2: 'TM',
    flag: 'https://www.countryflags.io/TM/flat/24.png',
  },
  {
    name: 'Turquía',
    dialCode: '+90',
    isoCode3: 'TUR',
    isoCode2: 'TR',
    flag: 'https://www.countryflags.io/TR/flat/24.png',
  },
  {
    name: 'Tuvalu',
    dialCode: '+688',
    isoCode3: 'TUV',
    isoCode2: 'TV',
    flag: 'https://www.countryflags.io/TV/flat/24.png',
  },
  {
    name: 'Ucrania',
    dialCode: '+380',
    isoCode3: 'UKR',
    isoCode2: 'UA',
    flag: 'https://www.countryflags.io/UA/flat/24.png',
  },
  {
    name: 'Uganda',
    dialCode: '+256',
    isoCode3: 'UGA',
    isoCode2: 'UG',
    flag: 'https://www.countryflags.io/UG/flat/24.png',
  },
  {
    name: 'Uruguay',
    dialCode: '+598',
    isoCode3: 'URY',
    isoCode2: 'UY',
    flag: 'https://www.countryflags.io/UY/flat/24.png',
  },
  {
    name: 'Uzbekistán',
    dialCode: '+998',
    isoCode3: 'UZB',
    isoCode2: 'UZ',
    flag: 'https://www.countryflags.io/UZ/flat/24.png',
  },
  {
    name: 'Vanuatu',
    dialCode: '+678',
    isoCode3: 'VUT',
    isoCode2: 'VU',
    flag: 'https://www.countryflags.io/VU/flat/24.png',
  },
  {
    name: 'Venezuela',
    dialCode: '+58',
    isoCode3: 'VEN',
    isoCode2: 'VE',
    flag: 'https://www.countryflags.io/VE/flat/24.png',
  },
  {
    name: 'Vietnam',
    dialCode: '+84',
    isoCode3: 'VNM',
    isoCode2: 'VN',
    flag: 'https://www.countryflags.io/VN/flat/24.png',
  },
  {
    name: 'Wallis y Futuna',
    dialCode: '+681',
    isoCode3: 'WLF',
    isoCode2: 'WF',
    flag: 'https://www.countryflags.io/WF/flat/24.png',
  },
  {
    name: 'Yemen',
    dialCode: '+967',
    isoCode3: 'YEM',
    isoCode2: 'YE',
    flag: 'https://www.countryflags.io/YE/flat/24.png',
  },
  {
    name: 'Yibuti',
    dialCode: '+253',
    isoCode3: 'DJI',
    isoCode2: 'DJ',
    flag: 'https://www.countryflags.io/DJ/flat/24.png',
  },
  {
    name: 'Zambia',
    dialCode: '+260',
    isoCode3: 'ZMB',
    isoCode2: 'ZM',
    flag: 'https://www.countryflags.io/ZM/flat/24.png',
  },
  {
    name: 'Zimbabue',
    dialCode: '+263',
    isoCode3: 'ZWE',
    isoCode2: 'ZW',
    flag: 'https://www.countryflags.io/ZW/flat/24.png',
  },
];
